<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NovaPasta1\**" />
    <Compile Remove="NovaPasta2\**" />
    <Compile Remove="NovaPasta\**" />
    <Compile Remove="wwwroot\imagens\**" />
    <Content Remove="NovaPasta1\**" />
    <Content Remove="NovaPasta2\**" />
    <Content Remove="NovaPasta\**" />
    <Content Remove="wwwroot\imagens\**" />
    <EmbeddedResource Remove="NovaPasta1\**" />
    <EmbeddedResource Remove="NovaPasta2\**" />
    <EmbeddedResource Remove="NovaPasta\**" />
    <EmbeddedResource Remove="wwwroot\imagens\**" />
    <None Remove="NovaPasta1\**" />
    <None Remove="NovaPasta2\**" />
    <None Remove="NovaPasta\**" />
    <None Remove="wwwroot\imagens\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\images\0f0a85e2-80f3-42d8-82db-d3942c02d70d.jpg" />
    <Content Remove="wwwroot\images\6c1b7be8-c41c-4829-b615-ac4aa7470547.jpg" />
    <Content Remove="wwwroot\images\72457ea5-0c24-48ac-a08f-5dc8ed6ff28a.png" />
    <Content Remove="wwwroot\images\77e74837-cd3a-440f-a0ab-b79e0eaed910.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

</Project>
